In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [31]:
df_org = pd.read_csv('sample_submission.csv')
df_org

id  target    O2_1    O2_2   O2_3   O2_4   O2_5    O2_6   O2_7  NH4_1  \
0        0    8.59   7.500   9.000  9.545  9.265  8.110   8.430  7.150  0.180   
1        1    9.10  13.533  40.900  8.770  9.265  6.015  10.070  7.150  1.107   
2        2    8.21   3.710   5.420  8.770  9.265  4.550  10.070  7.150  0.020   
3        3    8.39   8.700   8.100  9.500  9.200  5.200   8.670  6.670  0.280   
4        4    8.07   8.050   8.650  7.960  9.265  3.290  10.070  7.150  0.360   
...    ...     ...     ...     ...    ...    ...    ...     ...    ...    ...   
3495  3495    8.08   6.250   8.300  7.795  9.265  5.690   8.555  6.335  0.565   
3496  3496    8.09   6.630   6.630  8.370  7.600  0.636   8.430  7.150  1.300   
3497  3497    9.95   8.367   8.433  8.770  6.170  5.800  10.400  7.200  0.430   
3498  3498    9.52  10.000   6.630  9.545  9.265  3.290   8.980  2.310  0.300   
3499  3499    8.51   8.500   8.100  9.545  9.265  8.110   9.805  7.150  0.215   

      ...   NO3_5  NO3_6  NO3_7  BOD5_1  BOD5_2  BOD5_3  BOD5_4  BOD5_5  \
0     ...   4.950  1.730  1.800   4.800   3.150  10.665  10.465  16.645   
1     ...  20.050  9.530  7.695   4.550   6.950   2.040   5.200   5.725   
2     ...   4.580  3.025  3.960   4.935   4.950   4.725   6.075   6.750   
3     ...   8.450  2.070  1.730   6.300   4.700   3.500   6.200   8.670   
4     ...   2.020  1.730  0.760   4.800   4.970   3.950   2.800   8.400   
...   ...     ...    ...    ...     ...     ...     ...     ...     ...   
3495  ...  14.575  0.636  1.640   4.235   4.100   2.800   3.950   7.695   
3496  ...   4.580  1.730  1.800   4.900   3.150   2.040   6.075   8.415   
3497  ...  20.050  1.440  1.800   4.867   4.833   4.725   4.950   8.400   
3498  ...  20.050  9.530  7.695  10.700   5.400   4.725   3.300   6.750   
3499  ...   3.070  1.730  1.800   1.720   2.520   2.040   2.040   8.415   

      BOD5_6  BOD5_7  
0      5.750   10.37  
1      2.950    2.23  
2      3.500    3.17  
3      2.900    7.37  
4      3.500    3.90  
...      ...     ...  
3495   3.540    2.50  
3496   2.155    2.90  
3497   6.625    4.20  
3498   6.625    5.00  
3499   2.950    2.27  

[3500 rows x 37 columns]

In [6]:
y = df.pop('target')

In [8]:
x = df.copy()

In [9]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2)

In [10]:
from sklearn.model_selection import cross_val_score

In [22]:
from sklearn.ensemble import RandomForestRegressor

rf = RandomForestRegressor(
       n_estimators=1000,
       max_depth=7,
       n_jobs=-1,
       random_state=42)

In [ ]:
scores = cross_val_score(rf, x, y, cv=5, scoring='neg_root_mean_squared_error')
scores

In [24]:
from sklearn.metrics import mean_squared_error

def test_on_data(x_train, x_test, y_train, y_test):
    rf = RandomForestRegressor(
       n_estimators=1000,
       max_depth=7,
       n_jobs=-1,
       random_state=42)

    rf.fit(x_train, y_train)
    preds = rf.predict(x_test)
    return mean_squared_error(y_test, preds)

def test_on_data_cv(x, y, cv=5):
    rf = RandomForestRegressor(
       n_estimators=1000,
       max_depth=7,
       n_jobs=-1,
       random_state=42)

    scores = cross_val_score(rf, x, y, cv=cv, scoring='neg_root_mean_squared_error')
    scores
    return scores

In [29]:
test_on_data(x_train, x_test, y_train, y_test)

1.216700643089571

In [30]:
test_on_data_cv(x, y)

array([-2.60530854, -1.02242654, -1.15858928, -1.01867542, -1.19399043])

In [47]:
df_s = df_org.sort_values(by='target', ascending=False)

In [48]:
y_sorted = df_s.pop('target')

In [49]:
y_sorted.clip(7, 16)

451     16.0
316     16.0
1530    16.0
1876    16.0
2160    16.0
        ... 
1625     7.0
797      7.0
1866     7.0
465      7.0
282      7.0
Name: target, Length: 3500, dtype: float64

In [50]:
x_sorted = df_s.loc[:, ['O2_1', 'O2_2', 'NH4_6', 'BOD5_5']]

In [51]:
test_on_data_cv(x_sorted, y_sorted.clip(7, 16))

array([-2.71851294, -0.85449824, -0.76145458, -0.86512775, -1.29799564])

In [52]:
test_on_data_cv(x.loc[:, ['O2_1', 'O2_2', 'NH4_6', 'BOD5_5']], y.clip(7, 16))

array([-0.95934667, -0.93405585, -1.01802161, -0.91261929, -0.90324019])

In [53]:
test_on_data_cv(x.loc[:, ['O2_1', 'O2_2', 'NH4_6', 'BOD5_5']], y)

array([-2.51013495, -1.0607497 , -1.15177204, -1.01520703, -1.18661673])

In [58]:
zy = (y-y.mean())/y.std()
test_on_data_cv(x.loc[:, ['O2_1', 'O2_2', 'NH4_6', 'BOD5_5']], zy)

array([-1.3339691 , -0.56203308, -0.61070258, -0.53762468, -0.62913539])

In [59]:
yc = y.clip(6, 20)
zy = (yc-yc.mean())/yc.std()
test_on_data_cv(x.loc[:, ['O2_1', 'O2_2', 'NH4_6', 'BOD5_5']], zy)

array([-0.73205932, -0.65467523, -0.76154017, -0.65581716, -0.67667325])

In [60]:
zy

0       0.074718
1       0.416136
2      -0.179672
3      -0.059171
4      -0.273394
          ...   
3495   -0.266700
3496   -0.260005
3497    0.985165
3498    0.697303
3499    0.021162
Name: target, Length: 3500, dtype: float64

In [61]:
df_ex = df_org.copy()

In [63]:
df_ex[:] = 0

/var/folders/lb/05l0197j4wdgmqspj9s7bgjc0000gn/T/ipykernel_691/1214198663.py:1: DeprecationWarning: In a future version, `df.iloc[:, i] = newvals` will attempt to set the values inplace instead of always setting a new array. To retain the old behavior, use either `df[df.columns[i]] = newvals` or, if columns are non-unique, `df.isetitem(i, newvals)`
  df_ex[:] = 0


In [65]:
df_ex.target = zy

In [66]:
df_ex

id    target  O2_1  O2_2  O2_3  O2_4  O2_5  O2_6  O2_7  NH4_1  ...  \
0      0  0.074718     0     0     0     0     0     0     0      0  ...   
1      0  0.416136     0     0     0     0     0     0     0      0  ...   
2      0 -0.179672     0     0     0     0     0     0     0      0  ...   
3      0 -0.059171     0     0     0     0     0     0     0      0  ...   
4      0 -0.273394     0     0     0     0     0     0     0      0  ...   
...   ..       ...   ...   ...   ...   ...   ...   ...   ...    ...  ...   
3495   0 -0.266700     0     0     0     0     0     0     0      0  ...   
3496   0 -0.260005     0     0     0     0     0     0     0      0  ...   
3497   0  0.985165     0     0     0     0     0     0     0      0  ...   
3498   0  0.697303     0     0     0     0     0     0     0      0  ...   
3499   0  0.021162     0     0     0     0     0     0     0      0  ...   

      NO3_5  NO3_6  NO3_7  BOD5_1  BOD5_2  BOD5_3  BOD5_4  BOD5_5  BOD5_6  \
0         0      0      0       0       0       0       0       0       0   
1         0      0      0       0       0       0       0       0       0   
2         0      0      0       0       0       0       0       0       0   
3         0      0      0       0       0       0       0       0       0   
4         0      0      0       0       0       0       0       0       0   
...     ...    ...    ...     ...     ...     ...     ...     ...     ...   
3495      0      0      0       0       0       0       0       0       0   
3496      0      0      0       0       0       0       0       0       0   
3497      0      0      0       0       0       0       0       0       0   
3498      0      0      0       0       0       0       0       0       0   
3499      0      0      0       0       0       0       0       0       0   

      BOD5_7  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
3495       0  
3496       0  
3497       0  
3498       0  
3499       0  

[3500 rows x 37 columns]

In [67]:
x

id    O2_1    O2_2   O2_3   O2_4   O2_5    O2_6   O2_7  NH4_1  NH4_2  \
0        0   7.500   9.000  9.545  9.265  8.110   8.430  7.150  0.180  0.200   
1        1  13.533  40.900  8.770  9.265  6.015  10.070  7.150  1.107  1.027   
2        2   3.710   5.420  8.770  9.265  4.550  10.070  7.150  0.020  0.020   
3        3   8.700   8.100  9.500  9.200  5.200   8.670  6.670  0.280  0.270   
4        4   8.050   8.650  7.960  9.265  3.290  10.070  7.150  0.360  0.435   
...    ...     ...     ...    ...    ...    ...     ...    ...    ...    ...   
3495  3495   6.250   8.300  7.795  9.265  5.690   8.555  6.335  0.565  0.565   
3496  3496   6.630   6.630  8.370  7.600  0.636   8.430  7.150  1.300  2.200   
3497  3497   8.367   8.433  8.770  6.170  5.800  10.400  7.200  0.430  0.400   
3498  3498  10.000   6.630  9.545  9.265  3.290   8.980  2.310  0.300  0.200   
3499  3499   8.500   8.100  9.545  9.265  8.110   9.805  7.150  0.215  0.200   

      ...   NO3_5  NO3_6  NO3_7  BOD5_1  BOD5_2  BOD5_3  BOD5_4  BOD5_5  \
0     ...   4.950  1.730  1.800   4.800   3.150  10.665  10.465  16.645   
1     ...  20.050  9.530  7.695   4.550   6.950   2.040   5.200   5.725   
2     ...   4.580  3.025  3.960   4.935   4.950   4.725   6.075   6.750   
3     ...   8.450  2.070  1.730   6.300   4.700   3.500   6.200   8.670   
4     ...   2.020  1.730  0.760   4.800   4.970   3.950   2.800   8.400   
...   ...     ...    ...    ...     ...     ...     ...     ...     ...   
3495  ...  14.575  0.636  1.640   4.235   4.100   2.800   3.950   7.695   
3496  ...   4.580  1.730  1.800   4.900   3.150   2.040   6.075   8.415   
3497  ...  20.050  1.440  1.800   4.867   4.833   4.725   4.950   8.400   
3498  ...  20.050  9.530  7.695  10.700   5.400   4.725   3.300   6.750   
3499  ...   3.070  1.730  1.800   1.720   2.520   2.040   2.040   8.415   

      BOD5_6  BOD5_7  
0      5.750   10.37  
1      2.950    2.23  
2      3.500    3.17  
3      2.900    7.37  
4      3.500    3.90  
...      ...     ...  
3495   3.540    2.50  
3496   2.155    2.90  
3497   6.625    4.20  
3498   6.625    5.00  
3499   2.950    2.27  

[3500 rows x 36 columns]

In [68]:
columns = ['O2_1', 'O2_2', 'NH4_6', 'BOD5_5']
df_ex[columns] = x.loc[:, ['O2_1', 'O2_2', 'NH4_6', 'BOD5_5']]
df_ex

id    target    O2_1    O2_2  O2_3  O2_4  O2_5  O2_6  O2_7  NH4_1  ...  \
0      0  0.074718   7.500   9.000     0     0     0     0     0      0  ...   
1      0  0.416136  13.533  40.900     0     0     0     0     0      0  ...   
2      0 -0.179672   3.710   5.420     0     0     0     0     0      0  ...   
3      0 -0.059171   8.700   8.100     0     0     0     0     0      0  ...   
4      0 -0.273394   8.050   8.650     0     0     0     0     0      0  ...   
...   ..       ...     ...     ...   ...   ...   ...   ...   ...    ...  ...   
3495   0 -0.266700   6.250   8.300     0     0     0     0     0      0  ...   
3496   0 -0.260005   6.630   6.630     0     0     0     0     0      0  ...   
3497   0  0.985165   8.367   8.433     0     0     0     0     0      0  ...   
3498   0  0.697303  10.000   6.630     0     0     0     0     0      0  ...   
3499   0  0.021162   8.500   8.100     0     0     0     0     0      0  ...   

      NO3_5  NO3_6  NO3_7  BOD5_1  BOD5_2  BOD5_3  BOD5_4  BOD5_5  BOD5_6  \
0         0      0      0       0       0       0       0  16.645       0   
1         0      0      0       0       0       0       0   5.725       0   
2         0      0      0       0       0       0       0   6.750       0   
3         0      0      0       0       0       0       0   8.670       0   
4         0      0      0       0       0       0       0   8.400       0   
...     ...    ...    ...     ...     ...     ...     ...     ...     ...   
3495      0      0      0       0       0       0       0   7.695       0   
3496      0      0      0       0       0       0       0   8.415       0   
3497      0      0      0       0       0       0       0   8.400       0   
3498      0      0      0       0       0       0       0   6.750       0   
3499      0      0      0       0       0       0       0   8.415       0   

      BOD5_7  
0          0  
1          0  
2          0  
3          0  
4          0  
...      ...  
3495       0  
3496       0  
3497       0  
3498       0  
3499       0  

[3500 rows x 37 columns]

In [69]:
df_ex.to_csv('sub16.csv', index=False)

In [74]:
scaled_zy = (zy + 7)/(zy + 7).max() * 16

In [77]:
scaled_zy.min()

5.807993145801431

In [78]:
df_ex.target = scaled_zy
df_ex.to_csv('sub17.csv', index=False)

In [94]:
zp = zy + np.abs(zy.min())

In [95]:
zp.min()

0.0

In [96]:
zp.max()

9.372254279995005

In [105]:
zp_scaled_7_16 = ((zp/zp.max() * 9) + 7)

In [108]:
df_ex.target = zp_scaled_7_16
df_ex.to_csv('sub18.csv', index=False)